name: MMOBazaar
version: 0.1.1
main: dev.rusthero.mmobazaar.MMOBazaar
api-version: 1.13
author: rusthero
description: MMOBazaar brings Metin2-style market systems to Minecraft. Players can create personalized markets with item-based GUI trading.
website: https://github.com/rusthero/MMOBazaar
softdepend: [Vault]

commands:
  mmobazaar:
    description: MMOBazaar admin commands
    usage: /<command> give <player>
    permission: mmobazaar.admin
permissions:
  mmobazaar.admin:
    description: Allows admin use of MMOBazaar commands
    default: op